version: "3"


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    restart: "unless-stopped"
    depends_on:
      - mysql
    volumes:
      - .:/opt/app/server
    # networks:
    #   - my-network
  mysql:
    image: "mysql:8.0"
    restart: "always"
    container_name: "server_mysql"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    # networks:
    #   - my-network
