version: "3"


services:
  server:
    labels:
      kompose.service.type: LoadBalancer
    build:
      context: .
      dockerfile: Dockerfile
    image: pet-sever:latest
    container_name: "pet-server"
    ports:
      - "8010:8010"
      - "8012:8012"
    restart: "unless-stopped"
    depends_on:
      db:
        condition: service_healthy

    volumes:
      - .:/opt/app/server
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - HOST=db
      - DB_NAME=ecommerce
      - DB_PORT=3306
      - SERVER_PORT=8010
      - PPROF_PORT=8012

    # networks:
    #   - my-network
  db:
    image: "mysql:8.0"
    restart: "always"
    container_name: "db"
    # command: --default-authentication-plugin=caching_sha2_password instead
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_USER=user
      # - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=ecommerce
      # - MYSQL_ROOT_HOST=%
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes
      # networks:
      #   - my-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    # volumes:
    #   - my-db:/var/lib/mysql
    ports: 
      - '3306:3306'
# volumes:
#   my-db:
