apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backendconfig
  namespace: istio-mesh
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /ping
    port: 8010
