apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: merchant-backendconfig
  namespace: {{.Values.mesh.namespace}}
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /ping
    port: 5010
---
apiVersion: v1
kind: Service
metadata:
  name: merchant
  namespace: {{.Values.mesh.namespace}}
  annotations:
    cloud.google.com/backend-config: '{"default": "merchant-backendconfig"}'
    # cloud.google.com/app-protocols: '{"https":"HTTPS"}'
spec:
  type: NodePort
  ports:
    - name: "merchant-5010"
      port: 5010
      targetPort: 5010
      protocol: TCP
    - name: "merchant-5012"
      port: 5012
      targetPort: 5012
      protocol: TCP
  selector:
    app: merchant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant
  namespace: {{.Values.mesh.namespace}}
  labels:
    app: merchant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: merchant
    spec:
      containers:
        # - env:
        #     - name: DB_NAME
        #       value: ecommerce
        #     - name: DB_PORT
        #       value: "3306"
        #     - name: HOST
        #       # value: 192.168.58.2
        #       value: db
        #     - name: MYSQL_PASSWORD
        #       value: root
        #     - name: MYSQL_USER
        #       value: root
        #     - name: PPROF_PORT
        #       value: "8012"
        #     - name: SERVER_PORT
        #       value: "8010"
        - image: mohammedrashad/merchant:3
          name: image-merchant
          ports:
            - containerPort: 5010
              protocol: TCP
            - containerPort: 5012
              protocol: TCP
          envFrom:
            - configMapRef:
                name: config-server
          livenessProbe:
            httpGet:
              path: /ping
              port: 5010
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: 5010
            initialDelaySeconds: 60
            periodSeconds: 5
      restartPolicy: Always
