apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: products-backendconfig
  namespace: {{.Values.mesh.namespace}}
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /ping
    port: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: {{.Values.mesh.namespace}}
  annotations:
    cloud.google.com/backend-config: '{"default": "products-backendconfig"}'
    # cloud.google.com/app-protocols: '{"https":"HTTPS"}'
spec:
  type: NodePort
  ports:
    - name: "products-8010"
      port: 8010
      targetPort: 8010
      protocol: TCP
    - name: "products-8012"
      port: 8012
      targetPort: 8012
      protocol: TCP
  selector:
    app: products
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: {{.Values.mesh.namespace}}
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        # - env:
        #     - name: DB_NAME
        #       value: ecommerce
        #     - name: DB_PORT
        #       value: "3306"
        #     - name: HOST
        #       # value: 192.168.58.2
        #       value: db
        #     - name: MYSQL_PASSWORD
        #       value: root
        #     - name: MYSQL_USER
        #       value: root
        #     - name: PPROF_PORT
        #       value: "8012"
        #     - name: SERVER_PORT
        #       value: "8010"
        - image: mohammedrashad/products:1
          name: image-products
          ports:
            - containerPort: 8010
              protocol: TCP
            - containerPort: 8012
              protocol: TCP
          envFrom:
            - configMapRef:
                name: config-server
          livenessProbe:
            httpGet:
              path: /ping
              port: 8010
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: 8010
            initialDelaySeconds: 60
            periodSeconds: 5
      restartPolicy: Always
