# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: db-pv
#   namespace: {{.Values.mesh.namespace}}
#   labels:
#     app: db
# spec:
#   storageClassName: storage
#   storageClassName: {{ .Release.Name }}-storage
#   capacity:
#     storage: 10Gi  # Adjust the storage capacity as needed
#   accessModes:
#     - ReadOnlyMany
#   hostPath:
#     path: "/mnt/data/mysql"  # Replace with the actual path on your hostPath
# ---
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: {{.Values.mesh.namespace}}
  labels:
    app: db
spec:
  # AKS: default,managed-premium
  # GKE: standard
  # EKS: gp2 (custom)
  # Rook: rook-ceph-block,rook-ceph-fs
  storageClassName: {{ .Release.Name }}-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
