apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: random-product-gen-backendconfig
  namespace: {{.Values.mesh.namespace}}
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /ping
    port: 7010
---
apiVersion: v1
kind: Service
metadata:
  name: random-product-gen
  namespace: {{.Values.mesh.namespace}}
  annotations:
    cloud.google.com/backend-config: '{"default": "random-product-gen-backendconfig"}'
    # cloud.google.com/app-protocols: '{"https":"HTTPS"}'
spec:
  type: NodePort
  ports:
    - name: "random-product-gen-7010"
      port: 7010
      targetPort: 7010
      protocol: TCP
    - name: "random-prodcut-gen-7012"
      port: 7012
      targetPort: 7012
      protocol: TCP
  selector:
    app: random-product-gen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-product-gen
  namespace: {{.Values.mesh.namespace}}
  labels:
    app: random-product-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-product-gen
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: random-product-gen
      annotations:
      {{if eq .Values.mesh.namespace "linkerd-benchmark"}}
        config.linkerd.io/proxy-cpu-limit: 250m
        config.linkerd.io/proxy-cpu-request: 250m
        config.linkerd.io/proxy-memory-limit: 500Mi
        config.linkerd.io/proxy-memory-request: 500Mi
      {{end}}
      {{if eq .Values.mesh.namespace "istio-benchmark"}}
        sidecar.istio.io/proxyCPULimit: 250m
        sidecar.istio.io/proxyCPU: 250m
        sidecar.istio.io/proxyMemoryLimit: 500Mi
        sidecar.istio.io/proxyMemory: 500Mi
      {{end}}
    spec:
      containers:
        # - env:
        #     - name: DB_NAME
        #       value: ecommerce
        #     - name: DB_PORT
        #       value: "3306"
        #     - name: HOST
        #       # value: 192.168.58.2
        #       value: db
        #     - name: MYSQL_PASSWORD
        #       value: root
        #     - name: MYSQL_USER
        #       value: root
        #     - name: PPROF_PORT
        #       value: "8012"
        #     - name: SERVER_PORT
        #       value: "8010"
        - image: mohammedrashad/random-product-gen:3
          name: image-radnom-product-gen
          ports:
            - containerPort: 7010
              protocol: TCP
            - containerPort: 7012
              protocol: TCP
          envFrom:
            - configMapRef:
                name: config-server
          livenessProbe:
            httpGet:
              path: /ping
              port: 7010
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: 7010
            initialDelaySeconds: 60
            periodSeconds: 5
      restartPolicy: Always
      tolerations:
      - key: "app-family"
        operator: "Equal"
        value: {{.Values.mesh.app-family}}
        effect: "NoSchedule"
