version: "3"
services:
  frontend:
    tty: true
    stdin_open: true
    build:
      dockerfile: "Dockerfile.dev"
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
